import { useEffect, useRef } from 'react'
import { appName, appVersion } from '../../config/defaults'

export interface AboutModalProps {
  onClose: () => void
}

export function AboutModal({ onClose }: AboutModalProps) {
  const dialogRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handleKeyDown)
    dialogRef.current?.focus()
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  return (
    <div
      role="presentation"
      onClick={onClose}
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgb(15 23 42 / 0.5)',
        display: 'grid',
        placeItems: 'center',
        zIndex: 100,
        padding: '1rem',
      }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="about-title"
        tabIndex={-1}
        onClick={(event) => event.stopPropagation()}
        className="panel"
        style={{ maxWidth: '560px', width: '100%', maxHeight: '85vh', overflowY: 'auto', display: 'grid', gap: '0.75rem' }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <h2 id="about-title" style={{ margin: 0 }}>About {appName}</h2>
          <button type="button" className="ghost" onClick={onClose} aria-label="Close">✕</button>
        </div>

        <p>
          {appName} (v{appVersion}) generates urban block polygons from the OpenStreetMap road network: it downloads
          the streets in an area, nodes them into a topologically correct network, recursively removes dead-end
          branches, and polygonizes what remains into the closed loops between intersections - the urban blocks -
          along with their area, perimeter and compactness.
        </p>

        <p>
          Created by <strong>Maurizio Napolitano</strong> ("napo"). Source code:{' '}
          <a href="https://github.com/napo/urbanblocksbuilder" target="_blank" rel="noreferrer">
            github.com/napo/urbanblocksbuilder
          </a>.
        </p>

        <p>
          The core idea - iteratively pruning dead-end streets and polygonizing what's left to find block shapes -
          is inspired by Marcos Dione's article{' '}
          <a
            href="https://www.grulic.org.ar/~mdione/glob/posts/block-sizes-from-osm-data/"
            target="_blank"
            rel="noreferrer"
          >
            "Block sizes from OSM data"
          </a>
          , which describes deriving block sizes for Marseille using PostGIS and Shapely. This project reimplements
          that idea end-to-end in the browser, with JSTS for the topology, a Web Worker so it never blocks the UI,
          and an adaptive grid for acquiring larger areas from Overpass.
        </p>

        <div style={{ background: 'var(--color-surface-muted)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', padding: '0.65rem 0.85rem', fontSize: '0.85rem' }}>
          <strong>Data licence:</strong> all urban blocks, roads, and districts generated by this application are
          derived from OpenStreetMap data and are distributed under the{' '}
          <a href="https://opendatacommons.org/licenses/odbl/" target="_blank" rel="noreferrer">
            Open Database License (ODbL) 1.0
          </a>
          , © OpenStreetMap contributors. Every GeoJSON file this application exports includes this licence and
          attribution as metadata.
        </div>
      </div>
    </div>
  )
}
